name: sih_crowd_source
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.1
  image_picker: ^1.0.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  tflite_flutter: ^0.11.0
  image: ^4.1.0
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  firebase_auth: ^6.0.2
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  intl: ^0.20.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/classifier_model.tflite
    - assets/labels.txt
    - assets/logo.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
