import 'package:flutter/material.dart';
import 'package:sih_crowd_source/src/app.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:sih_crowd_source/firebase_options.dart'; // This file is generated by `flutterfire configure`

// The main entry point for the application.
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(); // Secure, auto-picks config from google-services.json
  runApp(const MyApp());
}
